server:
  port: 18081

dubbo:
  registry:
    # 挂载到 Spring Cloud 注册中心
    address: spring-cloud://localhost
  cloud:
    subscribed-services: sca-provider
  consumer:
    check: false

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.186.128:3306/yuhb-test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123456

  cloud:
    nacos:
      # Nacos 服务注册发现
      discovery:
        server-addr: 127.0.0.1:8848
    alibaba:
      seata:
      # Seata 事务组名称，对应file.conf文件中 vgroup_mapping.sca-customer-seata-tx-service-group
        tx-service-group: sca-customer-seata-tx-service-group

mybatis:
  mapper-locations: classpath:mapper/*.xml



