# For most projects, this workflow file will not need changing; you simply need
# to commit it to your repository.
#
# You may wish to alter this file to override the set of languages analyzed,
# or to provide custom queries or build logic.
#
# ******** NOTE ********
# We have attempted to detect the languages in your repository. Please check
# the `language` matrix defined below to confirm you have the correct set of
# supported CodeQL languages.
#
name: "E2E Test"

on: [ push,pull_request ]

jobs:
  run_e2e:
    name: Run E2E Test ${{ matrix.java }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [ 8, 11 ]
      fail-fast: false
      max-parallel: 2
    steps:
      - name: Check out code into
        uses: actions/checkout@v3

      - name: Clone skywalking e2e repository
        run: git clone https://github.com/apache/skywalking-infra-e2e.git skywalking-infra-e2e

      - name: Set up Go 1.18
        uses: actions/setup-go@v4
        with:
          go-version: 1.18
        id: go

      - name: Build e2e framework
        run: |
          cd skywalking-infra-e2e && make linux

      - name: Add script directory to PATH
        run: |
          cd skywalking-infra-e2e/bin/linux
          echo "export PATH=$PATH:$(pwd)" >> $GITHUB_PATH
          chmod 777 e2e
          cp e2e /usr/local/bin

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - name: prepare e2e tests
        run: | 
          cd e2e-test/scripts && sh prepare-test.sh

      - name: run e2e tests
        run: |
          cd e2e-test/scripts && sh test-run.sh
